### PR TITLE
Updated UniProt columns

### PR DESCRIPTION
**Pull request by thobalose**
Updated [UniProt columns](http://www.uniprot.org/help/uniprotkb_column_names).

### CODE REVIEW

**Comment by thobalose** [comment]
Hi @cokelaer ,

The build seems to be failing due to:

- [test_pride](https://github.com/cokelaer/bioservices/blob/master/test/test_pride.py)
  [pride](http://www.ebi.ac.uk/pride/ws/archive) returns a 404.

- [test_eutils](https://github.com/cokelaer/bioservices/blob/master/test/test_eutils.py)
       Commenting out: 
`assert dbinfo.Description == 'GTR database'` passes the test.

**Comment by cokelaer** [comment]
Thanks a lot Thoba, I've merged your pull request now. Just two comments. I'm guessing you removed some of the PRIDE tests because they failed on travis, which happens sometines, but they should work and I may add them back at least locally. Second point is that I've seen you have added a few changes related to coding style but sometimes there are different from what I tried to use (PEP8 coding style https://www.python.org/dev/peps/pep-0008/  ) ; for instance in method's prototype, I would write:

    def (a=1, b=2):

Note the space after the comma. In general, a good practice is to not change the coding style of the original code. Otherwise, thanks again for contributing !
      
.

**Comment by cokelaer** [comment]
Actually, all my apologies: I'm realising you have used PEP8 and fixed the existing code !!!
So, thanks again and please ignore my previous comment !!

**Comment by thobalose** [comment]
Thank you Thomas. :thumbsup:

**Pull request merged**
